model_name: "google/gemini-3-flash-preview"
api_key: ${oc.env:OPENROUTER_API_KEY}
base_url: "https://openrouter.ai/api/v1"
max_tokens: 32000
temperature: 0.7
agent_max_steps: 5
agent_name: "search_agent"
