model_name: "z-ai/glm-4.5-air:free"
api_key: ${oc.env:OPENROUTER_API_KEY}
base_url: "https://openrouter.ai/api/v1"
max_tokens: 32000
temperature: 0.3
agent_max_steps: 30
agent_name: "search_agent"
max_output_tokens: 30000
max_tool_threads: 10